### Variaables
@url = http://localhost:3000

@accountId = d85d6010-af1d-4d78-8735-d12ced83b31b


### POST - User/Create
POST {{url}}/user HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "name": "Walter Netto",
    "email": "walter.netto@request.com",
    "password": "12345678"
}


### GET - User/Get user by email

GET {{url}}/user?email=walter.netto@request.com HTTP/1.1

### POST - Account/create account
POST {{url}}/account HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "name": "Walter Netto",
    "type": "CURRENT",
    "balance": -1000
}

### GET - Account/Get account by ID
GET {{url}}/account?id={{accountId}} HTTP/1.1

