### Variaables
@url = http://localhost:3000

### POST - User
POST {{url}}/user HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "name": "",
    "email": "walter.netto@example.com",
    "password": "12345678"
}



