name: Pull Request na Main

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test || exit 1

      - name: Reviewers approval
        id: review
        run: echo "::set-output name=approved::true" 

      - name: Merge into main if approved
        if: steps.review.approved == 'true'
        uses: pascalgn/automerge-action@v0.13.0
        with:
          MERGE_METHOD: merge
          COMMIT_MESSAGE: "Merge pull request #$GITHUB_EVENT_PULL_REQUEST_NUMBER"
